services:
  invoice-extractor:
    container_name: invoice-extractor-container
    image: invoice-extractor:latest
    build:
      context: ..
      dockerfile: invoice_extractor/Dockerfile
    env_file: .env
    environment:
      - LOG_LEVEL=INFO
    ports:
      - "9091:9090"
    restart: unless-stopped
